version: "3"

services:
  redis:
    image: redis

  cli:
    image: ${CPYTHON_CLI_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - .:/code/faasm-cpython
      - /home/scs17/faasm-local/runtime_root:/usr/local/faasm/runtime_root
    working_dir: /code/faasm-cpython
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
