name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  formatting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    container:
      image: faasm/cpython:0.0.10
    defaults:
      run:
        working-directory: /code/python
    steps:
      - name: "Fetch ref"
        run: git fetch origin ${GITHUB_REF}:ci-branch
      - name: "Check out branch"
        run: git checkout --force ci-branch
      - name: "Install base requirements"
        run: pip3 install -r requirements.txt
      - name: "Install pyfaasm requirements"
        run: pip3 install -r pyfaasm/test_requirements.txt
      - name: "Python formatting check"
        run: ./bin/check_python.sh

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faasm/cpython:0.0.10
    defaults:
      run:
        working-directory: /code/python
    services:
      redis:
        image: redis
    steps:
      - name: "Fetch ref"
        run: git fetch origin ${GITHUB_REF}:ci-branch
      - name: "Check out branch"
        run: git checkout --force ci-branch
      - name: "Install base requirements"
        run: pip3 install -r requirements.txt
      - name: "Install pyfaasm requirements"
        run: pip3 install -r pyfaasm/test_requirements.txt
      - name: "Install pyfaasm"
        run: inv pyfaasm.native
      - name: "Run pyfaasm tests"
        run: inv pyfaasm.test
